export const CENTROS_SALUD = [
  {
    "id": "area-sanitaria-sr",
    "nombre": "Área Sanitaria San Rafael",
    "caps_nro": null,
    "tipo": "Coordinación Sanitaria",
    "zona": "Ciudad",
    "direccion": "Juan Agustín Maza 431, San Rafael",
    "telefono": "+54 260 442-4000",
    "web": "http://salud.mendoza.gov.ar/",
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Juan+Agustin+Maza+431+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Juan+Agustin+Maza+431+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-183",
    "nombre": "Centro de Salud N° 183 Barrio Valle Grande",
    "caps_nro": 183,
    "tipo": "Atención Primaria / Barrial",
    "zona": "Ciudad y Barrios",
    "direccion": "San Lorenzo y Las Heras, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=San+Lorenzo+y+Las+Heras+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=San+Lorenzo+y+Las+Heras+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-325",
    "nombre": "Centro de Salud N° 325 Ramón Carrillo",
    "caps_nro": 325,
    "tipo": "Atención Primaria / Barrial",
    "zona": "Ciudad y Barrios",
    "direccion": "O. de Rosas 1475, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=O.+de+Rosas+1475+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=O.+de+Rosas+1475+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-327",
    "nombre": "Centro de Salud N° 327 Barrio Constitución",
    "caps_nro": 327,
    "tipo": "Atención Primaria / Barrial",
    "zona": "Ciudad y Barrios",
    "direccion": "Alem 843, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Alem+843+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Alem+843+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-329",
    "nombre": "Centro de Salud N° 329 Teresa Scagliotti",
    "caps_nro": 329,
    "tipo": "Atención Primaria / Barrial",
    "zona": "Ciudad y Barrios",
    "direccion": "Los Plátanos 3000, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Los+Platanos+3000+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Los+Platanos+3000+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-334",
    "nombre": "Centro de Salud N° 334 Las Margaritas",
    "caps_nro": 334,
    "tipo": "Atención Primaria / Barrial",
    "zona": "Ciudad y Barrios",
    "direccion": "Callejón Rodríguez 2586, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Callejon+Rodriguez+2586+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Callejon+Rodriguez+2586+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-349",
    "nombre": "Centro de Salud N° 349 Villa Laredo",
    "caps_nro": 349,
    "tipo": "Atención Primaria / Barrial",
    "zona": "Ciudad y Barrios",
    "direccion": "Fleming y Leonardo Da Vinci, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Fleming+y+Leonardo+Da+Vinci+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Fleming+y+Leonardo+Da+Vinci+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-320",
    "nombre": "Centro de Salud N° 320 El Molino",
    "caps_nro": 320,
    "tipo": "Atención Primaria / Barrial",
    "zona": "Ciudad y Barrios",
    "direccion": "Vélez Sarsfield S/N, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Velez+Sarsfield+El+Molino+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Velez+Sarsfield+El+Molino+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-159",
    "nombre": "Centro de Salud N° 159 Isla Río Diamante",
    "caps_nro": 159,
    "tipo": "Atención Primaria / Barrial",
    "zona": "Ciudad y Barrios",
    "direccion": "Calle Amapola S/N, Isla Río Diamante, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Calle+Amapola+Isla+Rio+Diamante+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Calle+Amapola+Isla+Rio+Diamante+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-pueblo-diamante",
    "nombre": "Centro de Salud Municipal Pueblo Diamante",
    "caps_nro": null,
    "tipo": "Atención Primaria / Barrial",
    "zona": "Ciudad y Barrios",
    "direccion": "Barcala 1477, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Barcala+1477+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Barcala+1477+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-107",
    "nombre": "Centro de Salud N° 107 Villa 25 de Mayo",
    "caps_nro": 107,
    "tipo": "Atención Primaria / Distrital",
    "zona": "Distritos",
    "direccion": "Gobernador Ortega S/N, Villa 25 de Mayo, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Centro+de+Salud+107+Villa+25+de+Mayo+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Centro+de+Salud+107+Villa+25+de+Mayo+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-108",
    "nombre": "Centro de Salud N° 108 Goudge",
    "caps_nro": 108,
    "tipo": "Atención Primaria / Distrital",
    "zona": "Distritos",
    "direccion": "Moreno y Urquiza, Goudge, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Centro+de+Salud+108+Goudge+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Centro+de+Salud+108+Goudge+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-109",
    "nombre": "Centro de Salud N° 109 Las Malvinas",
    "caps_nro": 109,
    "tipo": "Atención Primaria / Distrital",
    "zona": "Distritos",
    "direccion": "Calle Pública Nº 1, Malvinas, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Centro+de+Salud+109+Las+Malvinas+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Centro+de+Salud+109+Las+Malvinas+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-110",
    "nombre": "Centro de Salud N° 110 Colonia Elena",
    "caps_nro": 110,
    "tipo": "Atención Primaria / Distrital",
    "zona": "Distritos",
    "direccion": "Calle Pública S/N Km 165, Colonia Elena, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Centro+de+Salud+110+Colonia+Elena+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Centro+de+Salud+110+Colonia+Elena+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-111",
    "nombre": "Centro de Salud N° 111 Rodolfo Iselín",
    "caps_nro": 111,
    "tipo": "Atención Primaria / Distrital",
    "zona": "Distritos",
    "direccion": "Dr. T. Schestakow S/N, La Llave Nueva, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Centro+de+Salud+111+La+Llave+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Centro+de+Salud+111+La+Llave+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-112",
    "nombre": "Centro de Salud N° 112 El Usillal",
    "caps_nro": 112,
    "tipo": "Atención Primaria / Distrital",
    "zona": "Distritos",
    "direccion": "Las Mercedes S/N, Las Paredes, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Centro+de+Salud+112+El+Usillal+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Centro+de+Salud+112+El+Usillal+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-113",
    "nombre": "Centro de Salud N° 113 Monte Comán",
    "caps_nro": 113,
    "tipo": "Atención Primaria / Distrital",
    "zona": "Distritos",
    "direccion": "Av. Mendoza S/N, Monte Comán, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Centro+de+Salud+113+Monte+Coman+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Centro+de+Salud+113+Monte+Coman+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-114",
    "nombre": "Centro de Salud N° 114 Villa Atuel",
    "caps_nro": 114,
    "tipo": "Atención Primaria / Distrital",
    "zona": "Distritos",
    "direccion": "Balbino Arizu 187, Villa Atuel, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Balbino+Arizu+187+Villa+Atuel+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Balbino+Arizu+187+Villa+Atuel+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-115",
    "nombre": "Centro de Salud N° 115 Real del Padre",
    "caps_nro": 115,
    "tipo": "Atención Primaria / Distrital",
    "zona": "Distritos",
    "direccion": "Neuquén S/N, Real del Padre, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Centro+de+Salud+115+Real+del+Padre+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Centro+de+Salud+115+Real+del+Padre+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-116",
    "nombre": "Centro de Salud N° 116 Cuadro Benegas",
    "caps_nro": 116,
    "tipo": "Atención Primaria / Distrital",
    "zona": "Distritos",
    "direccion": "Ruta Nacional 144 al 8880, Cuadro Benegas, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Ruta+Nacional+144+8880+Cuadro+Benegas+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Ruta+Nacional+144+8880+Cuadro+Benegas+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-117",
    "nombre": "Centro de Salud N° 117 El Nihuil",
    "caps_nro": 117,
    "tipo": "Atención Primaria / Distrital",
    "zona": "Distritos",
    "direccion": "Calle Alfredo Bufano S/N, El Nihuil, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Centro+de+Salud+117+El+Nihuil+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Centro+de+Salud+117+El+Nihuil+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-118",
    "nombre": "Centro de Salud N° 118 El Sosneado",
    "caps_nro": 118,
    "tipo": "Atención Primaria / Distrital",
    "zona": "Distritos",
    "direccion": "Ruta 40 S/N, El Sosneado, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Centro+de+Salud+118+El+Sosneado+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Centro+de+Salud+118+El+Sosneado+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-123",
    "nombre": "Centro de Salud N° 123 Punta del Agua",
    "caps_nro": 123,
    "tipo": "Atención Primaria / Distrital",
    "zona": "Distritos",
    "direccion": "Avenida de Mayo S/N, Punta del Agua, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Centro+de+Salud+123+Punta+del+Agua+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Centro+de+Salud+123+Punta+del+Agua+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-130",
    "nombre": "Centro de Salud N° 130 Salto de las Rosas",
    "caps_nro": 130,
    "tipo": "Atención Primaria / Distrital",
    "zona": "Distritos",
    "direccion": "Salto de las Rosas, Cañada Seca, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Centro+de+Salud+130+Salto+de+las+Rosas+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Centro+de+Salud+130+Salto+de+las+Rosas+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-158",
    "nombre": "Centro de Salud N° 158 Cuadro Nacional",
    "caps_nro": 158,
    "tipo": "Atención Primaria / Distrital",
    "zona": "Distritos",
    "direccion": "San Martín S/N, Cuadro Nacional, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Centro+de+Salud+158+Cuadro+Nacional+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Centro+de+Salud+158+Cuadro+Nacional+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-164",
    "nombre": "Centro de Salud N° 164 Capitán Montoya",
    "caps_nro": 164,
    "tipo": "Atención Primaria / Distrital",
    "zona": "Distritos",
    "direccion": "Capitán Montoya, Las Paredes, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Centro+de+Salud+164+Capitan+Montoya+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Centro+de+Salud+164+Capitan+Montoya+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-324",
    "nombre": "Centro de Salud N° 324 Los Claveles",
    "caps_nro": 324,
    "tipo": "Atención Primaria / Distrital",
    "zona": "Distritos",
    "direccion": "Los Claveles S/N, Cañada Seca, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Centro+de+Salud+324+Los+Claveles+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Centro+de+Salud+324+Los+Claveles+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-339",
    "nombre": "Centro de Salud N° 339 Francisca Strólogo",
    "caps_nro": 339,
    "tipo": "Atención Primaria / Distrital",
    "zona": "Distritos",
    "direccion": "El Chañaral S/N, Las Paredes, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Centro+de+Salud+339+El+Chañaral+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Centro+de+Salud+339+El+Chañaral+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-340",
    "nombre": "Centro de Salud N° 340 Manos Unidas La Pichana",
    "caps_nro": 340,
    "tipo": "Atención Primaria / Distrital",
    "zona": "Distritos",
    "direccion": "Ruta 166 y Luis Rojo, Cañada Seca, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Ruta+166+y+Luis+Rojo+La+Pichana+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Ruta+166+y+Luis+Rojo+La+Pichana+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-344",
    "nombre": "Centro de Salud N° 344 Juan Manuel García",
    "caps_nro": 344,
    "tipo": "Atención Primaria / Distrital",
    "zona": "Distritos",
    "direccion": "Ruta 146, Cuadro Bombal, Cuadro Nacional, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Ruta+146+Cuadro+Bombal+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Ruta+146+Cuadro+Bombal+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "caps-345",
    "nombre": "Centro de Salud N° 345 Colonia Gelman",
    "caps_nro": 345,
    "tipo": "Atención Primaria / Distrital",
    "zona": "Distritos",
    "direccion": "La Llave, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Centro+de+Salud+345+Colonia+Gelman+La+Llave+San+Rafael",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Centro+de+Salud+345+Colonia+Gelman+La+Llave+San+Rafael&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "hospital-schestakow",
    "nombre": "Hospital Teodoro J. Schestakow",
    "caps_nro": null,
    "tipo": "Hospital Público de Alta Complejidad",
    "zona": "Ciudad y Barrios",
    "direccion": "Cmte. Torres 150, San Rafael",
    "telefono": "+54 260 424-0300",
    "web": null,
    "redes": [
      {
        "plataforma": "Facebook",
        "url": "https://m.facebook.com/hospitalteodorojschestakow/"
      }
    ],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Hospital+Teodoro+J.+Schestakow+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Hospital+Teodoro+J.+Schestakow+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "policlinica-san-rafael",
    "nombre": "Policlínica San Rafael",
    "caps_nro": null,
    "tipo": "Clínica Privada / Ambulatorio",
    "zona": "Ciudad y Barrios",
    "direccion": "Av. Hipólito Yrigoyen 985, San Rafael",
    "telefono": "+54 260 443-3333",
    "web": "http://www.policlinicasanrafael.com/",
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Policlinica+San+Rafael+Av.+Hipolito+Yrigoyen+985",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Policlinica+San+Rafael+Av.+Hipolito+Yrigoyen+985&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "clinica-ciudad",
    "nombre": "Clínica Ciudad San Rafael",
    "caps_nro": null,
    "tipo": "Clínica Privada / Ambulatorio",
    "zona": "Ciudad y Barrios",
    "direccion": "Av. El Libertador 254, San Rafael",
    "telefono": "+54 260 442-1161",
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Clinica+Ciudad+Av.+El+Libertador+254+San+Rafael",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Clinica+Ciudad+Av.+El+Libertador+254+San+Rafael&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "hospital-eva-peron",
    "nombre": "Hospital Eva Perón",
    "caps_nro": null,
    "tipo": "Hospital Público / Regional",
    "zona": "Distritos",
    "direccion": "Calle Pública S/N (o República S/N), Jaime Prats, San Rafael",
    "telefono": "+54 2625 49-5000",
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Hospital+Eva+Peron+Jaime+Prats+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Hospital+Eva+Peron+Jaime+Prats+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "hospital-espanol",
    "nombre": "Hospital Español del Sur Mendocino",
    "caps_nro": null,
    "tipo": "Hospital Privado / Alta Complejidad",
    "zona": "Ciudad y Barrios",
    "direccion": "Av. El Libertador 950, San Rafael",
    "telefono": "+54 260 408-0000",
    "web": "https://www.hesm.org/",
    "redes": [
      {
        "plataforma": "WhatsApp",
        "url": "https://wa.me/5492604498763"
      }
    ],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Hospital+Español+del+Sur+Mendocino+Av.+El+Libertador+950+San+Rafael",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Hospital+Español+del+Sur+Mendocino+Av.+El+Libertador+950+San+Rafael&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "fuesmen-sr",
    "nombre": "FUESMEN (Sede San Rafael)",
    "caps_nro": null,
    "tipo": "Centro Ambulatorio / Diagnóstico y Alta Complejidad",
    "zona": "Ciudad y Barrios",
    "direccion": "Emilio Civit 150, San Rafael",
    "telefono": "+54 260 443-4111",
    "web": "https://www.fuesmen.edu.ar/sede-san-rafael/",
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=FUESMEN+Emilio+Civit+150+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=FUESMEN+Emilio+Civit+150+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  },
  {
    "id": "cms9-san-rafael",
    "nombre": "Centro Médico Sanitario CMS 9",
    "caps_nro": null,
    "tipo": "Centro Ambulatorio / Atención Primaria",
    "zona": "Ciudad y Barrios",
    "direccion": "Gral. Paz 841, San Rafael",
    "telefono": null,
    "web": null,
    "redes": [],
    "map_url": "https://www.google.com/maps/search/?api=1&query=Centro+Medico+Sanitario+Gral.+Paz+841+San+Rafael+Mendoza",
    "map_embed": "<iframe width='100%' height='200' src='https://maps.google.com/maps?q=Centro+Medico+Sanitario+Gral.+Paz+841+San+Rafael+Mendoza&t=&z=15&ie=UTF8&iwloc=&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>"
  }
];
